export const DEPARTMENTS = [
  'Advertising Department',
  'AI Department',
  'Accounting and Finance Department',
  'Admin Department',
  'Creatives and Design Department',
  'Digital Commerce Division',
  'Digital Department',
  'Executive Department',
  'Human Resources Department',
  'Importation Department',
  'Liaison Department',
  'Logistics Department',
  'Marketing Department',
  'Operations Department',
  'Pedia Clinic Department',
  'PR Marketing Department',
  'Premium Home and Lifestyle Division / Mobility Household System Division',
  'Sales and Marketing',
  'Sales Department',
  'Technical Department',
  'Utility Department',
  'Warehouse Department',
  'Zion - Sales Department'
];

export const POSITIONS = [
  'Accountant',
  'Ads Specialist',
  'Advertising Associate',
  'AI Specialist and Automation',
  'Admin Assistant',
  'Admin Head',
  'Admin Head - Regional',
  'Admin Manager OIC',
  'Admin Officer - OIC',
  'Audit Head',
  'Brand Communication Talent',
  'CEO/President',
  'Chief Finance Officer',
  'Chief of Operations',
  'Chief of Staff',
  'Chief Strategy Officer',
  'Clinic Secretary',
  'Creative Production Manager / Managing Director of LiveClick+',
  'Customer Service Representative',
  'Delivery Operations Assistant',
  'Digital and Creatives Director',
  'Director of Digital Commerce and Live Sales',
  'Door Lock Installer',
  'Graphic Artist',
  'HR Assistant',
  'Human Resources Manager',
  'Import Key Account Head',
  'In-house Project Manager',
  'IT Support Technician / Field Support Specialist',
  'Liaison / Accountant',
  'Liaison Officer',
  'Livestreamer',
  'Logistic Driver',
  'Logistics Driver',
  'Logistics Head',
  'Logistics Personnel',
  'Logistics Supervisor',
  'Managing Director',
  'Marketing and Admin Associate',
  'Marketing Associate',
  'Marketing Director',
  'Marketing Lead',
  'Mechanic',
  'Medical Aesthetician',
  'Multimedia Head',
  'OBS OPERATOR',
  'Operations Manager',
  'Operations Staff',
  'PR Marketing',
  'Project Manager / Associate Project Manager (IBS)',
  'Regional Operations Manager - Cebu',
  'Regional Operations Manager - Davao',
  'Roving Sales',
  'Sales Admin Assistant',
  'Sales Admin Associate',
  'Sales Advisor',
  'Sales and Admin Assistant',
  'Sales and Marketing Associate',
  'Sales and Operations Director',
  'Sales Associate',
  'Sales Head',
  'Sales Head - External',
  'Sales Head - Internal',
  'Sales Manager - External',
  'Sales Manager - Internal',
  'Secretary',
  'Senior Accountant',
  'Senior CFO',
  'Senior Sales and Admin',
  'Senior Warehouse Staff',
  'Smart door lock installer',
  'Tax and Accounting Head',
  'Technical Admin',
  'Technical Admin Head',
  'Technical and Logistics Admin',
  'Technical and Logistics Head',
  'Technical Head - External',
  'Technical Head - Internal',
  'Technical Installer Team Leader',
  'Technical Personnel',
  'Technical Personnel / Logistics Personnel',
  'Treasury Head',
  'Utility Personnel',
  'Videographer & Video Editor',
  'Videographer and Video Editor',
  'Warehouse Admin Assistant',
  'Warehouse Manager / Admin Head - Luzon',
  'Warehouse Personnel',
  'Warehouse Supervisor'
];
